import { AmortizationPeriod, LoanInput } from './loan-calculations';
import * as XLSX from 'xlsx';

export function downloadCSV(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
}

export function generateAmortizationCSV(schedule: AmortizationPeriod[]): string {
  const headers = [
    'Period', 'Date', 'Opening Balance', 'Drawdown', 'Interest Accrual',
    'Principal Paid', 'Interest Paid', 'Closing Balance', 'Cumulative Interest', 'Status'
  ];
  const rows = schedule.map(p => [
    p.periodNumber, p.date, p.openingBalance, p.drawdownAmount,
    p.interestAccrual, p.principalPaid, p.interestPaid,
    p.closingBalance, p.cumulativeInterest, p.status
  ]);
  return [headers, ...rows].map(r => r.join(',')).join('\n');
}

export function exportToExcel(
  schedule: AmortizationPeriod[], 
  loanInput: LoanInput, 
  auditTrail: any[]
) {
  const wb = XLSX.utils.book_new();

  const convention = loanInput.dayCountConvention ?? 'ACT/365';
  const totalInterest = schedule.length > 0 ? schedule[schedule.length - 1].cumulativeInterest : 0;
  const totalPrincipalPaid = schedule.reduce((s, p) => s + p.principalPaid, 0);
  const totalInterestPaid  = schedule.reduce((s, p) => s + p.interestPaid, 0);
  const totalDrawdowns = (loanInput.drawdowns ?? []).reduce((sum, d) => sum + d.amount, 0);

  // --- SHEET 1: PARAMETERS & SUMMARY ---
  const summaryRows: (string | number)[][] = [
    ['LOAN ACCRUAL SCHEDULE — IFRS 9 EIR METHOD'],
    [],
    ['Export Details'],
    ['Export Generated By', 'LoanGuard EIR Engine'],
    ['Export Timestamp', new Date().toISOString()],
    [],
    ['Facility Core Parameters'],
    ['Facility Name',        loanInput.loanName       ?? '—'],
    ['Currency',             loanInput.currency        ?? 'USD'],
    ['Start Date',           loanInput.startDate],
    ['Term (Months)',        loanInput.termInMonths],
    ['Base Principal',       loanInput.principalAmount],
    ['Annual Interest Rate', `${loanInput.annualInterestRate}%`],
    ['Day Count Convention', convention],
    ['Maturity Type',      loanInput.isBullet ? 'Bullet' : 'Amortizing'],
    [],
    ['Facility Lifetime Totals'],
    ['Total Base Principal', loanInput.principalAmount],
    ['Total Incremental Drawdowns', totalDrawdowns],
    ['Total Gross Facility', loanInput.principalAmount + totalDrawdowns],
    ['Total Interest Accrued', totalInterest],
    ['Total Principal Repaid', totalPrincipalPaid],
    ['Total Interest Settled', totalInterestPaid],
    ['Final Closing Balance',  schedule.length > 0 ? schedule[schedule.length - 1].closingBalance : 'N/A'],
  ];

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryRows);
  summarySheet['!cols'] = [{ wch: 30 }, { wch: 35 }];
  XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary & Parameters');

  // --- SHEET 2: AMORTIZATION SCHEDULE ---
  const scheduleHeaders = [
    'Period', 'Period End Date', 'Opening Balance', 'Drawdown',
    'Interest Accrual', 'Principal Paid', 'Interest Paid', 'Total Payment',
    'Closing Balance', 'Cumulative Interest', 'Status',
  ];

  const scheduleData = schedule.map(p => [
    p.periodNumber,
    p.date,
    p.openingBalance,
    p.drawdownAmount,
    p.interestAccrual,
    p.principalPaid,
    p.interestPaid,
    p.totalPayment,
    p.closingBalance,
    p.cumulativeInterest,
    p.status
  ]);

  const scheduleSheet = XLSX.utils.aoa_to_sheet([scheduleHeaders, ...scheduleData]);
  const numFmt = '#,##0.00';
  scheduleSheet['!cols'] = [
    { wch: 8  }, { wch: 15 }, { wch: 18 }, { wch: 18 },
    { wch: 18 }, { wch: 16 }, { wch: 16 }, { wch: 16 },
    { wch: 18 }, { wch: 20 }, { wch: 15 },
  ];
  
  const range = XLSX.utils.decode_range(scheduleSheet['!ref'] || 'A1');
  for(let R = range.s.r + 1; R <= range.e.r; ++R) {
    for(let C = 2; C <= 9; ++C) {
      const cell_address = {c:C, r:R};
      const cell_ref = XLSX.utils.encode_cell(cell_address);
      if(scheduleSheet[cell_ref]) {
        scheduleSheet[cell_ref].t = 'n';
        scheduleSheet[cell_ref].z = numFmt;
      }
    }
  }

  scheduleSheet['!freeze'] = { xSplit: 0, ySplit: 1, state: 'frozen' };
  XLSX.utils.book_append_sheet(wb, scheduleSheet, 'Amortization Ledger');
  
  // --- SHEET 3: AUDIT TRAIL ---
  const auditHeaders = ['Timestamp', 'Action Type', 'Details', 'User'];
  const auditData = auditTrail.map(e => [
    e.timestamp,
    e.actionType,
    e.details,
    e.user
  ]).reverse();

  const auditSheet = XLSX.utils.aoa_to_sheet([auditHeaders, ...auditData]);
  auditSheet['!cols'] = [{ wch: 25 }, { wch: 25 }, { wch: 70 }, { wch: 20 }];
  auditSheet['!freeze'] = { xSplit: 0, ySplit: 1, state: 'frozen' };
  XLSX.utils.book_append_sheet(wb, auditSheet, 'Audit Trail');

  // --- WRITE FILE ---
  XLSX.writeFile(wb, `${loanInput.loanName || 'Loan_Schedule'}_Export.xlsx`);
}
